### ISSUE TITLE
Plugin not loading by default if installed with plugin manager

### ISSUE THREAD

**Issue by vincentzhezhang** [ericpruitt/tmux.vim#1]
Thanks for the handy plugin.
There is a small issue though: by default, if it's installed via plugin manager, it won't be loaded, because the directory structure is like:

```
tmux.vim
  │
  ...
  └── vim
      ├── ftdetect
      │   └── tmux.vim
      ├── ftplugin
      │   └── tmux.vim
      └── syntax
          └── tmux.vim
```
A workaround if you use `vim-plug` is:
`Plug 'ericpruitt/tmux.vim', { 'do': 'ln -sf vim/* .' }`

Maybe the default directory structure can be changed?

**Comment by ericpruitt** [comment]
I don't use any plugin managers myself because I use nearly-stock Vim. What structure is needed to make this work out of the box?

**Comment by vincentzhezhang** [comment]
The simplest change would be: remove the `vim` directory, put `ftdetect`, `ftplugin` and `syntax` folders directly under the project root.

**Comment by ericpruitt** [comment]
I don't want to do that because I like having the syntax input and output separate. I was under the impression you could specify subdirectories with plugin managers, something along the lines of "ericpruitt/tmux.vim/vim" as the source. Is that not the case or is it something supported by a minority of plugin managers? What are the more complicated solutions that wouldn't require me to pull the files out of the "vim/" directory but would still be automatic for people using plugin managers?

**Comment by vincentzhezhang** [comment]
Make sense.
In this case, I can't think of any better solution other than put instructions for common vim plugin managers. Unless we can have a reliable way to detect which plugin manager is used to install `tmux.vm`

**Comment by anowlcalledjosh** [comment]
If you're not planning to change this, instructions for common plugin managers (or at least a hint that users will need to do something special) in the README would be appreciated. The main plugin managers I know of all support this, so I don't think keeping the file structure like this is unreasonable.

Examples:

vim-plug: `Plug 'ericpruitt/tmux.vim', {'rtp': 'vim'}`

Vundle: `Plugin 'ericpruitt/tmux.vim', {'rtp': 'vim/'}`

dein.vim: `call dein#add('ericpruitt/tmux.vim', {'rtp': 'vim'})`

[vim-plug]: https://github.com/junegunn/vim-plug
[Vundle]: https://github.com/VundleVim/Vundle.vim

**Comment by ericpruitt** [comment]
Thanks, @anowlcalledjosh. I have added these examples in e2edb4d4d870b27c5e979c048f14dd6537addede. Please take a look.

**Comment by anowlcalledjosh** [comment]
Awesome, thanks!
