### ISSUE TITLE
Support for {}-strings

### ISSUE THREAD

**Issue by latricewilgus** [ericpruitt/tmux.vim#14]
tmux 3.0 introduces {}-strings. From tmux(1):
```
     Command arguments may be specified as strings surrounded by single (')
     quotes, double quotes (") or braces ({}).  This is required when the ar‐
     gument contains any special character.  Single and double quoted strings
     cannot span multiple lines except with line continuation.  Braces can
     span multiple lines.
```
It would be nice to support these in some way, e.g. highlight as string. Or introduce a new highlighting group/colour-flavour for these kinds of strings.

**Comment by ericpruitt** [comment]
I'm not particularly good at Vim Script, and I pillaged much of the syntax file from other people. I'll try to look into this and the other issues you reported at some point, but if you'd like to see this and your other requested changes implemented any time soon, your best bet would be to submit a pull requests -- which I would happily accept.

**Comment by latricewilgus** [comment]
I'm also no expert. I did some copy an pasting and came up with this:

```
syn region tmuxDoubleQuotedString start=+"+ skip=+\\\\\|\\"\|\\$+ excludenl end=+"+ end='$' contains=tmuxFormatString
syn region tmuxSingleQuotedString start=+'+ skip=+\\\\\|\\'\|\\$+ excludenl end=+'+ end='$' contains=tmuxFormatString
" Uncomment for highlighting as a string, comment out for highlighting as code.
"syn region tmuxBracesString start=+{+ end=+}+ contains=@tmuxStrings,tmuxFormatString
" If not using the syn region tmuxBracesString, we can use this to highlight the start and the end braces of a string.
"syn match tmuxBracesString /[{}]/
syn cluster tmuxStrings contains=tmuxDoubleQuotedString,tmuxSingleQuotedString,tmuxBracesString

"[...]

hi def link tmuxSingledQuoteString tmuxString
hi def link tmuxDoubledQuoteString tmuxString
hi def link tmuxBracesString      tmuxString
hi def link tmuxString            String
```
Remarks:
* single and double quoted strings must be closed inside of brace-strings. (This seems not to be mentioned in tmux(1) but a test "display {'}" results in an error. In particular, the following are not strings which are not yet terminated:
`{'}`, `{"}`, `{"}"`
* I renamed the different types of strings into a cluster for easier reference. It seems Vim does not support linking a cluster-name to a highlighting group.

I'm not sure how to highlight the BracesString. I added the tmuxFormatString highlights as that seems uncontroversial.
For the controversal part consider these two examples:
```
# from tmux(1)
bind x if-shell "true" {
    if-shell "true" {
        display "true!"
    }
}
```
and
```
display-message {Hello World!}
```
The second example clearer screams for being highlighted like a string (usually in redish).
The first example, however, looks better if the {...} would not be highlighted at all, so that the normal highlighting kicks in and the keywords if-shell, display are displayed in a different color than the strings "true" and "true!".

If we do not highlight the braces and its content, we could only highlight the braces as string using
```
syn match tmuxBracesString /[{}]/
```
(instead of the `syn region tmuxBracesString ...`)

All in all, I have no clue what would be more appropriate. So I leave it up to you (that's why there is no pull request but you can just copy paste the snippets above).

**Comment by ericpruitt** [comment]
The must recent versions of tmux require that text within braces must be valid tmux configuration syntax rather than arbitrary strings (https://github.com/tmux/tmux/issues/2841) which obsolesces this issue unless I'm missing something, so I'm closing this.
