### ISSUE TITLE
tmux.conf.local not detected

### ISSUE THREAD

**Issue by allumik** [ericpruitt/tmux.vim#20]
As I am using the oh-my-tmux configuration from [gpakosz/.tmux](https://github.com/gpakosz/.tmux), my main configuration file is actually `.tmux.conf.local`. Standard vim configuration (without vim-polyglot) still uses the general conf highlighting here, but with this plugin it does not apply any kind of syntax highlighting at all.

I added this line
```
autocmd BufNewFile,BufRead {.,}tmux.conf.* setfiletype tmux
```
to my `init.vim` and it works for now. I suggest adding it to `ftdetect.vim` to support all kinds of modded configurations, if the wildcard does not cause any problems.

**Comment by gpakosz** [comment]
Hello there 👋

`.tmux.conf.local` is not the "main configuration file" per se, but indeed it's nicer when it's detected as a tmux configuration file.

It used to work before 6d9a56423269d630802eb2aa60c4de701578a024

**Comment by blueyed** [comment]
@gpakosz thanks for the reference.
The old pattern used there before was `{.,}tmux*.conf*` (https://github.com/ericpruitt/tmux.vim/commit/6d9a56423269d630802eb2aa60c4de701578a024#diff-dae19d580ce8d4d8e7699050ed5bfbb9b17748629a5044291b7112dd9401d18cL1).

**Comment by ericpruitt** [comment]
I'll revert the ftdetect pattern to `{.,}tmux*.conf*`.

**Comment by ericpruitt** [comment]
This should be addressed by d3211bcae1e9b350186f01b8541cb2adda65dbc2. Please take a look at let me know if there are any issues.

**Comment by gpakosz** [comment]
Thank you @ericpruitt 👍

**Comment by allumik** [comment]
Tested it and it is working now, thanks :)
