### ISSUE TITLE
display-popup, popup became tmux command since tmux 3.1c

### ISSUE THREAD

**Issue by haolian9** [ericpruitt/tmux.vim#21]
changes can be found [in here](https://github.com/tmux/tmux/blob/master/CHANGES#L374)

**Comment by ericpruitt** [comment]
I don't understand what this issue is about. Both commands are listed in the syntax file already.

**Comment by haolian9** [comment]
oh, sorry, my bad, i was thought those were missing in here, since those did not exist in nvim 0.5 runtime/syntax/tmux.vim.
