### ISSUE TITLE
More than one bracketed var on the same line shows as a error

### ISSUE THREAD

**Issue by derekschrock** [ericpruitt/tmux.vim#25]
A line with more than one bracketed var appears as an error:

  `var4=${_var1}${_var2}`

This appears to be valid syntax.

Also, see screenshot with the above, valid syntax assignments, and other valid error lines.

```tmux
var1=$_var3
var2=$_var3$_var4
var3=${_var1}$_var2
var4=${_var1}${_var2}    # not an error
var4=${_var1}${_var2     # valid error
var5=foo
var6=bar
var7=${_var3***}         # valid error
var8=${_var3}

# vi: set ft=tmux:
```

![Screenshot 2024-09-02 at 8 09 47 PM](https://github.com/user-attachments/assets/3cc941f3-0a22-4981-aeeb-93606e8bcd02)

Init. guess is this too greedy? https://github.com/ericpruitt/tmux.vim/blob/master/vim/syntax/tmux.vim#L40

**Comment by ericpruitt** [comment]
Thanks for reporting this. The issue should be fixed. I will submit a PR to the Vim repository later.
