### ISSUE TITLE
collaboration with tmux-plugins/vim-tmux?

### ISSUE THREAD

**Issue by davidosomething** [ericpruitt/tmux.vim#8]
There's another tmux config syntax and feature plugin at https://github.com/tmux-plugins/vim-tmux
Worth combining efforts?

**Comment by ericpruitt** [comment]
I personally don't have an interest in the non-syntax features that repository provides, and I don't want to maintain a repository consisting mostly of code I don't use. My entire repo is BSD licensed, so the maintainers of tmux-plugins/vim-tmux are welcome to adapt my scripts.
